# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

platform :ios do
  desc "Run Tests for iOS"
  lane :test do
    run_tests( 
      workspace: "WhiteLabelECommerce.xcworkspace",
      scheme: "ECommerce (iOS) Debug-Production"
    )
  end
end

platform :mac do 
  desc "Run Tests for macOS"
  lane :test do
    run_tests(
      workspace: "WhiteLabelECommerce.xcworkspace",
      scheme: "ECommerce (macOS) Debug-Production"
    )
  end
end
