pod 'SwiftLint'

target 'WhiteLabelECommerce (iOS)' do
  platform :ios, '14.0'
  use_frameworks!

  target 'WhiteLabelECommerceTests(iOS)' do
    inherit! :complete
  end
end

target 'WhiteLabelECommerce (macOS)' do
  platform :osx, '11.0'
  use_frameworks!
  target 'WhiteLabelECommerceTests(mac)' do
    inherit! :complete
  end
end
