name: Pull request
on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches:    
      - 'main'
  
jobs:
  test:
    runs-on: macos-11.6
    timeout-minutes: 15
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1.99.0
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - name: Bundle install
        run: bundle install
      - name: Pod install
        run: bundle exec pod install
      - name: Test - iOS
        run: bundle exec fastlane ios test
      - name: Test - macOS
        run: bundle exec fastlane mac test
